---
include:
  default:
    - profile::openstack::identity
    - profile::openstack::resource::dataporten
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::logging::rsyslog::client

profile::openstack::identity::manage_openidc: true

profile::openstack::openrc::filename: '/root/keystonerc_admin'

profile::openstack::identity::keystone_config:
  DEFAULT/secure_proxy_ssl_header:
    value:  'HTTP_X_FORWARDED_PROTO'

profile::openstack::identity::roles_extra:
  - user

profile::openstack::resource::dataporten::manage_dataporten: true
profile::openstack::resource::dataporten::domain:
  dataporten:
    ensure:       present
    description:  'Federated users from Dataporten'
    is_default:   false

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

openstack_version: 'mitaka' #FIXME
