---
include:
  default:
    - profile::dns::ns
    - profile::dns::rndc_key
    - profile::logging::rsyslog::client

profile::dns::rndc_key::create_admin_key:    true
profile::dns::rndc_key::create_mdns_key:     true
profile::dns::rndc_key::host_is_bind_server: true

profile::dns::ns::internal_zone: "test02.uhdc.no"

# Name servers in zone file
profile::dns::ns::name_servers:
  - "ns.test02.uhdc.no"
  - "ns.test01.uhdc.no"

# Forward zones
profile::dns::ns::fw_zones:
  internal:
    zone: "test02.uhdc.no"
    filename: "test02.uhdc.no.zone"
  frontend:
    zone: "iaas.uio.no"
    filename: "iaas.uio.no.zone"

# Reverse zones
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.28.0.0/16"
    origin: "28.172"
    filename: "reverse-172.28"
  public:
    cidr: "10.100.0.0/16"
    origin: "100.10"
    filename: "reverse-10.100"
