---
include:
  default:
    - profile::dns::ns
    - profile::dns::rndc_key
    - profile::logging::rsyslog::client

profile::dns::create_admin_key: true
profile::dns::create_mdns_key:  true

profile::dns::ns::internal_zone: "dev.iaas.intern"
