---
include:
  default:
    - profile::dns::ns
    - profile::dns::rndc_key
    - profile::logging::rsyslog::client

profile::dns::rndc_key::rndc_key_name:   "admin"
profile::dns::rndc_key::rndc_key_secret: "%{hiera('dns::rndc_secret_admin')}"

profile::dns::ns::internal_zone: "dev.iaas.intern"
